version: "2"

services:
  py2:
    build:
      context: .
      dockerfile: Dockerfile-py2
    volumes:
      - .:/src
    environment:
      PYTHONPATH: /src
      PYTHONUNBUFFERED: "True"
    working_dir: /src
    user: 1000:1000

  py3:
    build:
      context: .
      dockerfile: Dockerfile-py3
    volumes:
      - .:/src
    environment:
      PYTHONPATH: /src
      PYTHONUNBUFFERED: "True"
    working_dir: /src
    user: 1000:1000
