#!/usr/bin/env python3
import os
import io
import re

import sphinx_rtd_theme

here = os.path.abspath(os.path.dirname(__file__))

extensions = ["sphinx.ext.autodoc", "sphinx.ext.viewcode"]

source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "rel2tree"
# copyright = ""
# author = ""
today_fmt = "%Y-%m-%d"

with io.open(os.path.join(here, "../../setup.py"), encoding="utf-8") as f:
    version = re.search("^VERSION = '(.*)'$", f.read(), re.M).group(1)
# version = os.environ.get("VERSION")
# release = version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
# language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
# exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
# pygments_style = 'sphinx'
pygments_style = "trac"

# If true, `todo` and `todoList` produce output, else they produce nothing.
# todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

html_theme = "sphinx_rtd_theme"
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
